/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shivb
 */
public class Cancellation extends javax.swing.JFrame {

    /**
     * Creates new form Cancellation
     */
    String username="shiv";
    String mobile="";
    public Cancellation(String username,String Mobile) {
        this.username=username;
        this.mobile=Mobile;
        System.out.println(this.username);
        initComponents();
        
        
        
        
    }
    public ArrayList<User> userList(int a){
            ArrayList<User> userList=new ArrayList<>();
             try{
         Class.forName("com.mysql.cj.jdbc.Driver");  
        Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3307/task1","root",""); 
           Statement statement;
            statement = con.createStatement();            
            ResultSet rs;
            rs = statement.executeQuery("select * from booking where bookingID='"+a+"' ");
            User user;
            
           while (rs.next()) {
               user=new User(rs.getInt("BookingID"),rs.getString("Customer_Name"),rs.getString("Mobile_No"),rs.getString("Train_ID"),rs.getString("Train_Name"),rs.getString("Source_Address"),rs.getString("Destination_Address"),rs.getString("Date"));
               userList.add(user);
              
           }
                 
           
           statement.close();
            con.close();
           
     }catch(Exception e){
         System.out.println(e);
     
     }
             return userList;
    }
    
    public void  loadcombo(){
   try{
         Class.forName("com.mysql.cj.jdbc.Driver");  
        Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3307/task1","root",""); 
           Statement statement;
            statement = con.createStatement();            
            ResultSet resultSet;
            resultSet = statement.executeQuery(
                "select BookingID from Booking ");
            
            
           while (resultSet.next()) {
                String bookID = resultSet.getString("BookingID");
                cancelrequest.addItem(bookID);
                
            }
           
           statement.close();
            con.close();
           
     }catch(Exception e){
         System.out.println(e);
     }}
    public void show_user(int a){
        
        ArrayList<User> list=userList(a);
        DefaultTableModel model=(DefaultTableModel)showTable.getModel();
        Object[] row=new Object[9];
        for(int i=0;i<list.size();i++){
            row[0]=list.get(i).getBookingID();
            row[1]=list.get(i).getCustomer_Name();
            row[2]=list.get(i).getMobile_No();
            row[3]=list.get(i).getTrain_ID();
            row[4]=list.get(i).getTrain_Name();
            row[5]=list.get(i).getSource_Address();
            row[6]=list.get(i).getDestination_Address();
            row[7]=list.get(i).getDate();
            model.addRow(row);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        showTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cancelrequest = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1024, 728));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showTable.setForeground(new java.awt.Color(255, 255, 255));
        showTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookingID", "Customer_Name", "Mobile_No", "Train_ID", "Train_Name", "Source_Address", "Destination_Address", "Date"
            }
        ));
        showTable.setBackground(new java.awt.Color(0,0,0));
        jScrollPane1.setViewportView(showTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 880, 90));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select BookingID for Cancel request");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 30));

        cancelrequest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        loadcombo();
        getContentPane().add(cancelrequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, -1));

        jButton1.setText("Show Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jButton2.setText("Cancel booked Ticket");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 160, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shivb\\Downloads\\1139035.jpg")); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 728));

        jMenu1.setText("Dashboard");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cancellation Request");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenu2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu2KeyPressed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
                        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2KeyPressed

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
    dashboard ds=new dashboard(this.username,mobile);
    dispose();
    ds.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MenuSelected

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String bookid= (String) cancelrequest.getSelectedItem();
       int bk=Integer.parseInt(bookid);
       showTable.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] { },
    new String [] {
        "BookingID", "Customer_Name", "Mobile_No", "Train_ID", "Train_Name", "Source_Address", "Destination_Address", "Date"
    }));
       
        show_user(bk);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String bookid= (String) cancelrequest.getSelectedItem();
       int bk=Integer.parseInt(bookid);
       int flag=0;
       int result = JOptionPane.showConfirmDialog(null,"Sure? You want to cancel selected ticket?", "Swing Tester",
               JOptionPane.YES_NO_OPTION,
               JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                flag=1;
            }else{ 
              flag=0;
            }
         
         if(flag==1){
         try{
         Class.forName("com.mysql.cj.jdbc.Driver");  
        Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3307/task1","root",""); 
           Statement statement;
            statement = con.createStatement();            
            
           String sql="Delete from booking where bookingID='"+bk+"'";
           statement.executeUpdate(sql);
           statement.close();
            con.close();
            showTable.setModel(new javax.swing.table.DefaultTableModel(
    new Object [][] { },
    new String [] {
        "BookingID", "Customer_Name", "Mobile_No", "Train_ID", "Train_Name", "Source_Address", "Destination_Address", "Date"
    }));
    cancelrequest.removeAllItems();
    loadcombo();
            
           
     }catch(Exception e){
         System.out.println(e);
     } 
         }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cancelrequest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable showTable;
    // End of variables declaration//GEN-END:variables
}
