/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author shivb
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    String username;
    String mobile;
    public dashboard(String a,String b) {
        mobile=b;
         try{
         Class.forName("com.mysql.cj.jdbc.Driver");  
        Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3307/task1","root",""); 
           Statement statement;
            statement = con.createStatement();            
            ResultSet resultSet;
            resultSet = statement.executeQuery(
                "select * from login where userID='"+a+"'");
            
            
           while (resultSet.next()) {
                this.username = resultSet.getString("userName");
            }
           
           statement.close();
            con.close();
       if(username==null){
        this.username=a;
        }
           
     }catch(Exception e){
         System.out.println(e);
     }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DashName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DashMob = new javax.swing.JTextField();
        SelectTbtn = new javax.swing.JButton();
        Destadd = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Startadd = new javax.swing.JComboBox<>();
        Dateselect = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        SubmitDash = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1024, 728));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0,0,0,150));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome " +username);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 28, 490, 50));

        DashName.setBackground(new java.awt.Color(0,0,0,150));
        DashName.setForeground(new java.awt.Color(255, 255, 255));
        DashName.setText(username);
        DashName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(DashName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 240, 30));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 90, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 60, 30));

        Tname.setForeground(new java.awt.Color(255, 255, 255));
        Tname.setBackground(new java.awt.Color(0,0,0,150));
        Tname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(Tname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 240, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mobile No:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 90, 30));

        SelectedID.setForeground(new java.awt.Color(255, 255, 255));
        SelectedID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        SelectedID.setBackground(new java.awt.Color(0,0,0,150));
        SelectedID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3307/task1","root","");
            Statement statement;
            statement = con.createStatement();
            ResultSet resultSet;
            resultSet = statement.executeQuery(
                "select Tno from traindetails ");

            while (resultSet.next()) {
                String tno = resultSet.getString("Tno");
                SelectedID.addItem(tno);

            }

            statement.close();
            con.close();

        }catch(Exception e){
            System.out.println(e);
        }
        SelectedID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectedIDActionPerformed(evt);
            }
        });
        jPanel1.add(SelectedID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 212, 210, 30));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Train No :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 90, 20));

        DashMob.setForeground(new java.awt.Color(255, 255, 255));
        DashMob.setBackground(new java.awt.Color(0,0,0,150));
        DashMob.setText(mobile);
        DashMob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(DashMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 240, 30));

        SelectTbtn.setText("Select Train ");
        SelectTbtn.setBorder(null);
        SelectTbtn.setBackground(new java.awt.Color(255,255,255,150));
        SelectTbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectTbtnActionPerformed(evt);
            }
        });
        jPanel1.add(SelectTbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 100, 30));

        Destadd.setForeground(new java.awt.Color(255, 255, 255));
        Destadd.setBackground(new java.awt.Color(0,0,0,150));
        Destadd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        Destadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(Destadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 150, 30));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Train Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 90, 20));

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Starting Station :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 120, 20));

        Startadd.setForeground(new java.awt.Color(255, 255, 255));
        Startadd.setBackground(new java.awt.Color(0,0,0,150));
        Startadd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        Startadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(Startadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 150, 30));

        Dateselect.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Dateselect.setForeground(new java.awt.Color(255, 255, 255));
        Dateselect.setBackground(new java.awt.Color(0,0,0,150));
        jPanel1.add(Dateselect, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 140, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Destination Station :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 150, 20));

        SubmitDash.setText("Book Train");
        SubmitDash.setBackground(new java.awt.Color(255,255,255,150));
        SubmitDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitDashActionPerformed(evt);
            }
        });
        jPanel1.add(SubmitDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 950, 560));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shivb\\Downloads\\1139035.jpg")); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 728));

        jMenu1.setText("Dashboard");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cancellation Request");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenu2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu2KeyPressed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu2KeyPressed
       // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2KeyPressed

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
       Cancellation cl=new Cancellation(this.username,mobile);
        dispose();
        cl.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
    dashboard ds=new dashboard(this.username,mobile);
    dispose();
    ds.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MenuSelected

    private void SelectedIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectedIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectedIDActionPerformed

    private void SelectTbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectTbtnActionPerformed
    String selected= String.valueOf(SelectedID.getSelectedItem());
    
    String Trainname="";
    String route="";
        try{
         Class.forName("com.mysql.cj.jdbc.Driver");  
        Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3307/task1","root",""); 
           Statement statement;
            statement = con.createStatement();            
            ResultSet resultSet;
            resultSet = statement.executeQuery(
                "select Tname,route from traindetails where Tno='"+selected+"'  ");
            
            
            while (resultSet.next()) {
                Trainname = resultSet.getString("Tname");
                route=resultSet.getString("route");
              
                
                
            }
            String[] Stations = route.split(",");
            Tname.setText(Trainname);
           
            
            
             for (int i = 0; i < Stations.length; i++){   
            Startadd.addItem(Stations[i]);
            Destadd.addItem(Stations[i]);
        } 
           
           statement.close();
            con.close();
           
     }catch(Exception e){
         System.out.println(e);
     }// TODO add your handling code here:
    }//GEN-LAST:event_SelectTbtnActionPerformed

    private void SubmitDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitDashActionPerformed
          Date userdate = Dateselect.getDate();
           String strDate = DateFormat.getDateInstance().format(userdate);
             
            String username=DashName.getText();
                        

            String userMob=DashMob.getText();
                        

            String trainID=String.valueOf(SelectedID.getSelectedItem());
            String trainname=Tname.getText();
            String src=String.valueOf(Startadd.getSelectedItem());
            String dest=String.valueOf(Destadd.getSelectedItem());
             if(!src.equals(dest)){
        try{
         Class.forName("com.mysql.cj.jdbc.Driver");  
        Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3307/task1","root",""); 
           Statement statement;
            statement = con.createStatement();            
           String sql="INSERT INTO booking(Customer_Name,Mobile_No,Train_ID,Train_Name,Source_Address, Destination_Address, Date)"+"Values('"+username+"','"+userMob+"','"+trainID+"','"+trainname+"','"+src+"','"+dest+"','"+strDate+"')";
           statement.executeUpdate(sql);
            
            
           
           JOptionPane.showMessageDialog(null    ,"Train Booked");
        
           statement.close();
            con.close();
           
     }catch(Exception e){
         System.out.println(e);
     }
             // TODO add your handling code here:
     
        }else{
             JOptionPane.showMessageDialog(null    ,"Train Source and Destination address can not Same");
             }// TODO add your handling code here:
    }//GEN-LAST:event_SubmitDashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new dashboard().setVisible(true);
//            }
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DashMob;
    private javax.swing.JTextField DashName;
    private com.toedter.calendar.JDateChooser Dateselect;
    private javax.swing.JComboBox<String> Destadd;
    private javax.swing.JButton SelectTbtn;
    private final javax.swing.JComboBox<String> SelectedID = new javax.swing.JComboBox<>();
    private javax.swing.JComboBox<String> Startadd;
    private javax.swing.JButton SubmitDash;
    private javax.swing.JTextField Tname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
