/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author shivb
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    
    public Registration() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        regUser = new javax.swing.JTextField();
        regNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        regMail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        regPass = new javax.swing.JPasswordField();
        regconpass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        regbtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        regUserID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1024, 728));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0,0, 0,150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Register Here");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 170, 60));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UserID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, 30));

        regUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUserActionPerformed(evt);
            }
        });
        jPanel1.add(regUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 200, 30));

        regNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNumActionPerformed(evt);
            }
        });
        jPanel1.add(regNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 200, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mobile No :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 120, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Re-enter Password :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 190, 30));

        regMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regMailActionPerformed(evt);
            }
        });
        jPanel1.add(regMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 200, 30));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 120, 30));
        jPanel1.add(regPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 272, 190, 30));

        regconpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regconpassActionPerformed(evt);
            }
        });
        jPanel1.add(regconpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 170, 30));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 120, 30));

        regbtn.setBackground(new java.awt.Color(51, 51, 255));
        regbtn.setText("Register");
        regbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtnActionPerformed(evt);
            }
        });
        jPanel1.add(regbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 110, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("User Name :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 120, 30));

        regUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUserIDActionPerformed(evt);
            }
        });
        jPanel1.add(regUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 200, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 400, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shivb\\Downloads\\1139035.jpg")); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 728));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regUserActionPerformed

    private void regNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regNumActionPerformed

    private void regMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regMailActionPerformed

    private void regconpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regconpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regconpassActionPerformed

    private void regbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtnActionPerformed
        String userName=regUser.getText();
        String userID=regUserID.getText();
        String num=regNum.getText();    
        String email =regMail.getText();//TODO add your handling code here:
        String pass=regPass.getText();
        String conpass=regconpass.getText();
        if(pass.equals(conpass)){
        try{
         Class.forName("com.mysql.cj.jdbc.Driver");  
        Connection con=DriverManager.getConnection(  "jdbc:mysql://localhost:3307/task1","root",""); 
           Statement statement;
            statement = con.createStatement();            
           String sql="INSERT INTO login (userName,userID,mobileNO,emailID,password)"+"Values('"+userName+"','"+userID+"','"+num+"','"+email+"','"+pass+"')";
           statement.executeUpdate(sql);
            
            
           
            System.out.println("login.Registration.regbtnActionPerformed()");
           statement.close();
            con.close();
           
     }catch(Exception e){
         System.out.println(e);
     }
     dispose();
     LoginFrame lf=new LoginFrame();
     lf.setVisible(true);
        }
   
     

        
    }//GEN-LAST:event_regbtnActionPerformed

    private void regUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regUserIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField regMail;
    private javax.swing.JTextField regNum;
    private javax.swing.JPasswordField regPass;
    private javax.swing.JTextField regUser;
    private javax.swing.JTextField regUserID;
    private javax.swing.JButton regbtn;
    private javax.swing.JPasswordField regconpass;
    // End of variables declaration//GEN-END:variables
}
